### ISSUE TITLE
How to get the tree drawn by R?

### ISSUE THREAD

**Issue by ataravarice** [yosuken/ViPTreeGen#2]
I have tried this ViptreeGen and it is fast and convinient.

I get 5 folders:

drwxr-xr-x.  7 hxy zrlab   90 Sep 12 23:01 batch
drwxr-xr-x.  4 hxy zrlab   42 Sep 12 23:01 cat
drwxr-xr-x.  2 hxyzrlab   86 Sep 12 23:01 log
drwxr-xr-x. 71 hxy zrlab 4.0K Sep 12 22:59 node
drwxr-xr-x.  2 hxy zrlab  157 Sep 12 23:01 result

However, the phylogenetic tree in the ViPTree server project is far better than newick tree file.

I see the ViPtreeGen have deal the tree with R package. ape and phangorn 

Can anyone tell me how to generate a tree picture with R using files output by ViptreeGen? Is there some protocol about it?

**Comment by yosuken** [comment]
I'm sorry for the late reply. ViPTreeGen is focused on proteomic tree generation (output in the newick format). At the ViPTree web server, tree visualization is done by javascript (d3.js library), but this function is not included in ViPTreeGen. For tree visualization, please use the web server or other tools (for example, <a href="https://itol.embl.de/">iTOL</a>, <a href="http://tree.bio.ed.ac.uk/software/figtree/">FigTree</a>, or <a href="https://guangchuangyu.github.io/software/ggtree/">ggtree</a> for R)
