### ISSUE TITLE
Checkpointing or resuming analysis

### ISSUE THREAD

**Issue by lancewilson-monash** [yosuken/ViPTreeGen#3]
Looking through the documentation I can't find anything on resuming an analysis after a job is interrupted. For a really big analysis of more than a couple of days this becomes quite important. Can you suggest how to do this?

**Comment by yosuken** [comment]
Currently, 'resume a job' function is not implemented... I understand it requires quite long time for a huge dataset, and it is planned to develop a faster version (e.g., use of blast-alternative).
