### ISSUE TITLE
rake aborted!

### ISSUE THREAD

**Issue by snayfach** [yosuken/ViPTreeGen#8]
The program runs fine on a few sequences, but I get this error on a set of 500 viral genomes. Any clues what might be wrong? Reducing the number of threads does not help, only lowering the number of genomes.

> rake aborted!
> Command failed with status (1): [makeblastdb -dbtype nucl -hash_index -pars...]
> /global/cscratch1/sd/snayfach/projects/votudb/12.tool_compare/ViPTree/ViPTreeGen/ViPTreeGen.rake:371:in `block in <top (required)>'
> /global/cscratch1/sd/snayfach/projects/votudb/12.tool_compare/ViPTree/ViPTreeGen/ViPTreeGen.rake:120:in `block (2 levels) in <top (required)>'
> /global/cscratch1/sd/snayfach/projects/votudb/12.tool_compare/ViPTree/ViPTreeGen/ViPTreeGen.rake:119:in `each'
> /global/cscratch1/sd/snayfach/projects/votudb/12.tool_compare/ViPTree/ViPTreeGen/ViPTreeGen.rake:119:in `with_index'
> /global/cscratch1/sd/snayfach/projects/votudb/12.tool_compare/ViPTree/ViPTreeGen/ViPTreeGen.rake:119:in `block in <top (required)>'
> Tasks: TOP => 01-1.prep_for_tblastx
> (See full trace by running task with --trace)
>

**Comment by yosuken** [comment]
If it runs with ruby3, please try ruby2.x.

**Comment by snayfach** [comment]
I narrowed down the problem to a subset of sequences in my input. It appears the program is crashing due to the length of some headers in my sequence file.

This sequence caused failure: `>Family3_GokushovirinaeB_Zuo_F3_NODE_2597_length_5174_cov_4587029`
But worked after changing to: `>NODE_2597_length_5174`

Can you verify on your end? If so, would be helpful to include a check/warning or add something to the readme to save others time in the future.

**Comment by yosuken** [comment]
The failure was reproduced.
I removed unnecessary makeblastdb options that probably cause errors when sequence names are long.
The new version (v1.1.3) works well in my environment.
